# Generated by Django 4.2.9 on 2024-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number_description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('user_name', models.CharField(max_length=100)),
                ('commodity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrossFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number_description', models.CharField(max_length=255)),
                ('failure_count', models.IntegerField()),
                ('date_midpoint', models.DateField()),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
