# Generated by Django 4.2.9 on 2024-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('sku', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='failurerecord',
            name='customer',
            field=models.CharField(blank=True, default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='grossfailure',
            name='customer',
            field=models.CharField(blank=True, default='unknown', max_length=30),
        ),
    ]
