# Generated by Django 4.2.9 on 2024-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0003_failurerecord_submitted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFailureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number_description', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('user_name', models.CharField(max_length=100)),
                ('commodity', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, default='unknown', max_length=30)),
                ('submitted_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
